name: Run Tests

on: [pull_request]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
        os: [ubuntu-20.04, ubuntu-22.04]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python3 -m pip install -U pip
          python3 -m pip install --editable .[dev]
      - name: install yara
        run: sudo apt-get install yara
      - name: run pytest
        run: pytest
